### ISSUE TITLE
Translation to Brazilian Portuguese (PTBR) SpiffUI - Radials

### ISSUE THREAD

**Issue by BryanJuan1** [djhert/pz-mods#6]
Hello, I translated your mod to Brazilian Portuguese, I am happy to play with your mod thx:

[UI_PTBR.txt](https://github.com/hlfstr/pz-mods/files/10523158/UI_PTBR.txt)

**Comment by djhert** [comment]
Hello!  Sorry for the delay in my response.  I guess I need to review my notification settings for GitHub!
Thank you for your submitted translation!

Would you mind submitting a new pull request with your changed translations?  By making a pull request and merging your translation this way, you will forever be listed under the "Contributors" on this repository.  Otherwise, let me know and I'll grab the file you provided here. 

Thanks again!

**Comment by BryanJuan1** [comment]
Hello! Sorry for posting like an "issue," I did not know how GitHub worked, but I will make a pull request. 
Sorry about my English. 
And if you need help with more translation of your mods, I would be happy to help you.
